// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package dbsqlc

import (
	"context"
)

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_log (id, user_id, node_id, network_id, action, details)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAuditEntryParams struct {
	ID        string
	UserID    string
	NodeID    *string
	NetworkID *string
	Action    string
	Details   *string
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEntry,
		arg.ID,
		arg.UserID,
		arg.NodeID,
		arg.NetworkID,
		arg.Action,
		arg.Details,
	)
	return err
}

const listAuditForNetwork = `-- name: ListAuditForNetwork :many
SELECT a.id, a.user_id, a.node_id, a.network_id, a.action, a.details, a.created_at,
       u.email AS user_email, u.name AS user_name,
       n.hostname AS node_hostname
FROM audit_log a
LEFT JOIN users u ON u.id = a.user_id
LEFT JOIN nodes n ON n.id = a.node_id
WHERE a.network_id = ?1
  AND a.created_at >= ?2
  AND (?3 IS NULL OR a.action = ?3)
ORDER BY a.created_at DESC LIMIT ?4
`

type ListAuditForNetworkParams struct {
	NetworkID *string
	Since     int64
	Action    interface{}
	Limit     int64
}

type ListAuditForNetworkRow struct {
	ID           string
	UserID       string
	NodeID       *string
	NetworkID    *string
	Action       string
	Details      *string
	CreatedAt    int64
	UserEmail    *string
	UserName     *string
	NodeHostname *string
}

func (q *Queries) ListAuditForNetwork(ctx context.Context, arg ListAuditForNetworkParams) ([]ListAuditForNetworkRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditForNetwork,
		arg.NetworkID,
		arg.Since,
		arg.Action,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditForNetworkRow{}
	for rows.Next() {
		var i ListAuditForNetworkRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.NetworkID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserName,
			&i.NodeHostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditForUser = `-- name: ListAuditForUser :many
SELECT a.id, a.user_id, a.node_id, a.network_id, a.action, a.details, a.created_at,
       u.email AS user_email, u.name AS user_name,
       n.hostname AS node_hostname
FROM audit_log a
LEFT JOIN users u ON u.id = a.user_id
LEFT JOIN nodes n ON n.id = a.node_id
WHERE a.user_id = ?1
  AND a.created_at >= ?2
  AND (?3 IS NULL OR a.action = ?3)
ORDER BY a.created_at DESC LIMIT ?4
`

type ListAuditForUserParams struct {
	UserID string
	Since  int64
	Action interface{}
	Limit  int64
}

type ListAuditForUserRow struct {
	ID           string
	UserID       string
	NodeID       *string
	NetworkID    *string
	Action       string
	Details      *string
	CreatedAt    int64
	UserEmail    *string
	UserName     *string
	NodeHostname *string
}

func (q *Queries) ListAuditForUser(ctx context.Context, arg ListAuditForUserParams) ([]ListAuditForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditForUser,
		arg.UserID,
		arg.Since,
		arg.Action,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditForUserRow{}
	for rows.Next() {
		var i ListAuditForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.NetworkID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserName,
			&i.NodeHostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
