// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package dbsqlc

import (
	"context"
)

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_log (id, user_id, node_id, network_id, action, details)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAuditEntryParams struct {
	ID        string
	UserID    string
	NodeID    *string
	NetworkID *string
	Action    string
	Details   *string
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEntry,
		arg.ID,
		arg.UserID,
		arg.NodeID,
		arg.NetworkID,
		arg.Action,
		arg.Details,
	)
	return err
}

const listAuditForNetwork = `-- name: ListAuditForNetwork :many
SELECT id, user_id, node_id, network_id, action, details, created_at
FROM audit_log WHERE network_id = ? ORDER BY created_at DESC LIMIT ?
`

type ListAuditForNetworkParams struct {
	NetworkID *string
	Limit     int64
}

func (q *Queries) ListAuditForNetwork(ctx context.Context, arg ListAuditForNetworkParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditForNetwork, arg.NetworkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NodeID,
			&i.NetworkID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
