// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bundles.sql

package dbsqlc

import (
	"context"
)

const deleteExpiredBundles = `-- name: DeleteExpiredBundles :exec
DELETE FROM enrollment_bundles WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredBundles(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredBundles, expiresAt)
	return err
}

const getBundleByToken = `-- name: GetBundleByToken :one
SELECT id, node_id, download_token, downloaded, expires_at, created_at
FROM enrollment_bundles WHERE download_token = ? AND downloaded = 0 AND expires_at > ?
`

type GetBundleByTokenParams struct {
	DownloadToken string
	ExpiresAt     int64
}

func (q *Queries) GetBundleByToken(ctx context.Context, arg GetBundleByTokenParams) (EnrollmentBundle, error) {
	row := q.db.QueryRowContext(ctx, getBundleByToken, arg.DownloadToken, arg.ExpiresAt)
	var i EnrollmentBundle
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.DownloadToken,
		&i.Downloaded,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertBundle = `-- name: InsertBundle :exec
INSERT INTO enrollment_bundles (id, node_id, download_token, expires_at)
VALUES (?, ?, ?, ?)
`

type InsertBundleParams struct {
	ID            string
	NodeID        string
	DownloadToken string
	ExpiresAt     int64
}

func (q *Queries) InsertBundle(ctx context.Context, arg InsertBundleParams) error {
	_, err := q.db.ExecContext(ctx, insertBundle,
		arg.ID,
		arg.NodeID,
		arg.DownloadToken,
		arg.ExpiresAt,
	)
	return err
}

const markBundleDownloaded = `-- name: MarkBundleDownloaded :exec
UPDATE enrollment_bundles SET downloaded = 1 WHERE id = ?
`

func (q *Queries) MarkBundleDownloaded(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markBundleDownloaded, id)
	return err
}
