// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_codes.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const authorizeDeviceCode = `-- name: AuthorizeDeviceCode :execresult
UPDATE device_codes SET user_id = ?, network_id = ?, status = 'authorized'
WHERE user_code = ? AND status = 'pending' AND expires_at > ?
`

type AuthorizeDeviceCodeParams struct {
	UserID    *string
	NetworkID *string
	UserCode  string
	ExpiresAt int64
}

func (q *Queries) AuthorizeDeviceCode(ctx context.Context, arg AuthorizeDeviceCodeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, authorizeDeviceCode,
		arg.UserID,
		arg.NetworkID,
		arg.UserCode,
		arg.ExpiresAt,
	)
}

const completeDeviceCode = `-- name: CompleteDeviceCode :execresult
UPDATE device_codes SET status = 'completed' WHERE device_code = ? AND status = 'authorized'
`

func (q *Queries) CompleteDeviceCode(ctx context.Context, deviceCode string) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeDeviceCode, deviceCode)
}

const deleteExpiredDeviceCodes = `-- name: DeleteExpiredDeviceCodes :exec
DELETE FROM device_codes WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredDeviceCodes(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredDeviceCodes, expiresAt)
	return err
}

const getAuthorizedDeviceCode = `-- name: GetAuthorizedDeviceCode :one
SELECT device_code, user_code, user_id, network_id, status, expires_at
FROM device_codes WHERE device_code = ? AND status = 'authorized' AND expires_at > ?
`

type GetAuthorizedDeviceCodeParams struct {
	DeviceCode string
	ExpiresAt  int64
}

type GetAuthorizedDeviceCodeRow struct {
	DeviceCode string
	UserCode   string
	UserID     *string
	NetworkID  *string
	Status     string
	ExpiresAt  int64
}

func (q *Queries) GetAuthorizedDeviceCode(ctx context.Context, arg GetAuthorizedDeviceCodeParams) (GetAuthorizedDeviceCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthorizedDeviceCode, arg.DeviceCode, arg.ExpiresAt)
	var i GetAuthorizedDeviceCodeRow
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.UserID,
		&i.NetworkID,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const getDeviceCodeByCode = `-- name: GetDeviceCodeByCode :one
SELECT device_code, user_code, user_id, network_id, node_id, status, expires_at, created_at
FROM device_codes WHERE device_code = ?
`

func (q *Queries) GetDeviceCodeByCode(ctx context.Context, deviceCode string) (DeviceCode, error) {
	row := q.db.QueryRowContext(ctx, getDeviceCodeByCode, deviceCode)
	var i DeviceCode
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.UserID,
		&i.NetworkID,
		&i.NodeID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceCodeByUserCode = `-- name: GetDeviceCodeByUserCode :one
SELECT device_code, user_code, user_id, network_id, node_id, status, expires_at, created_at
FROM device_codes WHERE user_code = ? AND expires_at > ?
`

type GetDeviceCodeByUserCodeParams struct {
	UserCode  string
	ExpiresAt int64
}

func (q *Queries) GetDeviceCodeByUserCode(ctx context.Context, arg GetDeviceCodeByUserCodeParams) (DeviceCode, error) {
	row := q.db.QueryRowContext(ctx, getDeviceCodeByUserCode, arg.UserCode, arg.ExpiresAt)
	var i DeviceCode
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.UserID,
		&i.NetworkID,
		&i.NodeID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertDeviceCode = `-- name: InsertDeviceCode :exec
INSERT INTO device_codes (device_code, user_code, status, expires_at)
VALUES (?, ?, ?, ?)
`

type InsertDeviceCodeParams struct {
	DeviceCode string
	UserCode   string
	Status     string
	ExpiresAt  int64
}

func (q *Queries) InsertDeviceCode(ctx context.Context, arg InsertDeviceCodeParams) error {
	_, err := q.db.ExecContext(ctx, insertDeviceCode,
		arg.DeviceCode,
		arg.UserCode,
		arg.Status,
		arg.ExpiresAt,
	)
	return err
}

const setDeviceCodeNodeID = `-- name: SetDeviceCodeNodeID :exec
UPDATE device_codes SET node_id = ? WHERE device_code = ?
`

type SetDeviceCodeNodeIDParams struct {
	NodeID     *string
	DeviceCode string
}

func (q *Queries) SetDeviceCodeNodeID(ctx context.Context, arg SetDeviceCodeNodeIDParams) error {
	_, err := q.db.ExecContext(ctx, setDeviceCodeNodeID, arg.NodeID, arg.DeviceCode)
	return err
}
