// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dns_records.sql

package dbsqlc

import (
	"context"
)

const dNSRecordNameExists = `-- name: DNSRecordNameExists :one
SELECT COUNT(*) FROM dns_records WHERE network_id = ? AND name = ?
`

type DNSRecordNameExistsParams struct {
	NetworkID string
	Name      string
}

func (q *Queries) DNSRecordNameExists(ctx context.Context, arg DNSRecordNameExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, dNSRecordNameExists, arg.NetworkID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDNSRecord = `-- name: DeleteDNSRecord :exec
DELETE FROM dns_records WHERE id = ? AND network_id = ?
`

type DeleteDNSRecordParams struct {
	ID        string
	NetworkID string
}

func (q *Queries) DeleteDNSRecord(ctx context.Context, arg DeleteDNSRecordParams) error {
	_, err := q.db.ExecContext(ctx, deleteDNSRecord, arg.ID, arg.NetworkID)
	return err
}

const deleteDNSRecordsForNetwork = `-- name: DeleteDNSRecordsForNetwork :exec
DELETE FROM dns_records WHERE network_id = ?
`

func (q *Queries) DeleteDNSRecordsForNetwork(ctx context.Context, networkID string) error {
	_, err := q.db.ExecContext(ctx, deleteDNSRecordsForNetwork, networkID)
	return err
}

const getDNSRecord = `-- name: GetDNSRecord :one
SELECT id, network_id, name, nebula_ip, created_at
FROM dns_records WHERE id = ? AND network_id = ?
`

type GetDNSRecordParams struct {
	ID        string
	NetworkID string
}

func (q *Queries) GetDNSRecord(ctx context.Context, arg GetDNSRecordParams) (DnsRecord, error) {
	row := q.db.QueryRowContext(ctx, getDNSRecord, arg.ID, arg.NetworkID)
	var i DnsRecord
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.Name,
		&i.NebulaIp,
		&i.CreatedAt,
	)
	return i, err
}

const insertDNSRecord = `-- name: InsertDNSRecord :exec
INSERT INTO dns_records (id, network_id, name, nebula_ip) VALUES (?, ?, ?, ?)
`

type InsertDNSRecordParams struct {
	ID        string
	NetworkID string
	Name      string
	NebulaIp  string
}

func (q *Queries) InsertDNSRecord(ctx context.Context, arg InsertDNSRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertDNSRecord,
		arg.ID,
		arg.NetworkID,
		arg.Name,
		arg.NebulaIp,
	)
	return err
}

const listDNSRecordsForNetwork = `-- name: ListDNSRecordsForNetwork :many
SELECT id, network_id, name, nebula_ip, created_at
FROM dns_records WHERE network_id = ? ORDER BY name
`

func (q *Queries) ListDNSRecordsForNetwork(ctx context.Context, networkID string) ([]DnsRecord, error) {
	rows, err := q.db.QueryContext(ctx, listDNSRecordsForNetwork, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsRecord{}
	for rows.Next() {
		var i DnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.Name,
			&i.NebulaIp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
