// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

type ApiKey struct {
	ID         string
	UserID     string
	Name       string
	KeyHash    string
	LastUsedAt *int64
	CreatedAt  int64
}

type AuditLog struct {
	ID        string
	UserID    string
	NodeID    *string
	NetworkID *string
	Action    string
	Details   *string
	CreatedAt int64
}

type DeviceCode struct {
	DeviceCode string
	UserCode   string
	UserID     *string
	NetworkID  *string
	NodeID     *string
	Status     string
	ExpiresAt  int64
	CreatedAt  int64
}

type DnsRecord struct {
	ID        string
	NetworkID string
	Name      string
	NebulaIp  string
	CreatedAt int64
}

type EnrollmentBundle struct {
	ID            string
	NodeID        string
	DownloadToken string
	Downloaded    int64
	ExpiresAt     int64
	CreatedAt     int64
}

type Network struct {
	ID             string
	UserID         string
	Name           string
	Slug           string
	NebulaCaCert   []byte
	NebulaCaKey    []byte
	NebulaSubnet   *string
	ServerCert     []byte
	ServerKey      []byte
	LighthousePort *int64
	DnsDomain      string
	CreatedAt      int64
}

type NetworkInvite struct {
	ID        string
	NetworkID string
	CreatedBy string
	Code      string
	Role      string
	MaxUses   *int64
	UseCount  int64
	ExpiresAt *int64
	CreatedAt int64
}

type NetworkMember struct {
	ID        string
	NetworkID string
	UserID    string
	Role      string
	CreatedAt int64
}

type Node struct {
	ID                  string
	NetworkID           string
	Hostname            string
	Os                  string
	Arch                string
	NebulaCert          []byte
	NebulaKey           []byte
	NebulaIp            *string
	AgentToken          string
	EnrollmentToken     *string
	EnrollmentExpiresAt *int64
	AgentRealIp         *string
	NodeType            string
	ExposedPorts        *string
	DnsName             *string
	Status              string
	LastSeenAt          *int64
	CreatedAt           int64
}

type Session struct {
	Token     string
	UserID    string
	CreatedAt int64
	ExpiresAt int64
}

type User struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	GithubID     *string
	CreatedAt    int64
}
