// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: networks.sql

package dbsqlc

import (
	"context"
)

const deleteNetwork = `-- name: DeleteNetwork :exec
DELETE FROM networks WHERE id = ?
`

func (q *Queries) DeleteNetwork(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNetwork, id)
	return err
}

const getNetworkByID = `-- name: GetNetworkByID :one
SELECT id, user_id, name, slug, nebula_ca_cert, nebula_ca_key, nebula_subnet, server_cert, server_key, created_at
FROM networks WHERE id = ?
`

func (q *Queries) GetNetworkByID(ctx context.Context, id string) (Network, error) {
	row := q.db.QueryRowContext(ctx, getNetworkByID, id)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.NebulaCaCert,
		&i.NebulaCaKey,
		&i.NebulaSubnet,
		&i.ServerCert,
		&i.ServerKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertNetwork = `-- name: InsertNetwork :exec
INSERT INTO networks (id, user_id, name, slug, nebula_ca_cert, nebula_ca_key, nebula_subnet, server_cert, server_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNetworkParams struct {
	ID           string
	UserID       string
	Name         string
	Slug         string
	NebulaCaCert []byte
	NebulaCaKey  []byte
	NebulaSubnet *string
	ServerCert   []byte
	ServerKey    []byte
}

func (q *Queries) InsertNetwork(ctx context.Context, arg InsertNetworkParams) error {
	_, err := q.db.ExecContext(ctx, insertNetwork,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.NebulaCaCert,
		arg.NebulaCaKey,
		arg.NebulaSubnet,
		arg.ServerCert,
		arg.ServerKey,
	)
	return err
}

const listNetworksForUser = `-- name: ListNetworksForUser :many
SELECT id, user_id, name, slug, nebula_subnet, created_at
FROM networks WHERE user_id = ? ORDER BY created_at DESC
`

type ListNetworksForUserRow struct {
	ID           string
	UserID       string
	Name         string
	Slug         string
	NebulaSubnet *string
	CreatedAt    int64
}

func (q *Queries) ListNetworksForUser(ctx context.Context, userID string) ([]ListNetworksForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listNetworksForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNetworksForUserRow{}
	for rows.Next() {
		var i ListNetworksForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.NebulaSubnet,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxSubnetOctet = `-- name: MaxSubnetOctet :one
SELECT MAX(CAST(SUBSTR(nebula_subnet, 7, INSTR(SUBSTR(nebula_subnet, 7), '.') - 1) AS INTEGER))
FROM networks WHERE nebula_subnet IS NOT NULL
`

func (q *Queries) MaxSubnetOctet(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxSubnetOctet)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const networkSlugExists = `-- name: NetworkSlugExists :one
SELECT COUNT(*) FROM networks WHERE slug = ?
`

func (q *Queries) NetworkSlugExists(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, networkSlugExists, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}
