// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: network_invites.sql

package dbsqlc

import (
	"context"
)

const deleteExpiredInvites = `-- name: DeleteExpiredInvites :exec
DELETE FROM network_invites
WHERE expires_at IS NOT NULL AND expires_at < unixepoch()
`

func (q *Queries) DeleteExpiredInvites(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredInvites)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM network_invites WHERE id = ?
`

func (q *Queries) DeleteInvite(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInvite, id)
	return err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, network_id, created_by, code, role, max_uses, use_count, expires_at, created_at
FROM network_invites WHERE code = ?
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (NetworkInvite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByCode, code)
	var i NetworkInvite
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.CreatedBy,
		&i.Code,
		&i.Role,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementInviteUseCount = `-- name: IncrementInviteUseCount :exec
UPDATE network_invites SET use_count = use_count + 1 WHERE id = ?
`

func (q *Queries) IncrementInviteUseCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementInviteUseCount, id)
	return err
}

const atomicClaimInvite = `-- name: AtomicClaimInvite :execresult
UPDATE network_invites SET use_count = use_count + 1
WHERE code = ?
  AND (expires_at IS NULL OR expires_at > unixepoch())
  AND (max_uses IS NULL OR use_count < max_uses)
`

type AtomicClaimInviteResult struct {
	RowsAffected int64
}

func (q *Queries) AtomicClaimInvite(ctx context.Context, code string) (int64, error) {
	result, err := q.db.ExecContext(ctx, atomicClaimInvite, code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertInvite = `-- name: InsertInvite :exec
INSERT INTO network_invites (id, network_id, created_by, code, role, max_uses, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertInviteParams struct {
	ID        string
	NetworkID string
	CreatedBy string
	Code      string
	Role      string
	MaxUses   *int64
	ExpiresAt *int64
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) error {
	_, err := q.db.ExecContext(ctx, insertInvite,
		arg.ID,
		arg.NetworkID,
		arg.CreatedBy,
		arg.Code,
		arg.Role,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	return err
}

const listInvitesForNetwork = `-- name: ListInvitesForNetwork :many
SELECT id, network_id, created_by, code, role, max_uses, use_count, expires_at, created_at
FROM network_invites WHERE network_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListInvitesForNetwork(ctx context.Context, networkID string) ([]NetworkInvite, error) {
	rows, err := q.db.QueryContext(ctx, listInvitesForNetwork, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetworkInvite{}
	for rows.Next() {
		var i NetworkInvite
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.CreatedBy,
			&i.Code,
			&i.Role,
			&i.MaxUses,
			&i.UseCount,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
