// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: network_events.sql

package dbsqlc

import (
	"context"
)

const insertNetworkEvent = `-- name: InsertNetworkEvent :exec
INSERT INTO network_events (network_id, event_type, target_id, status, details, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertNetworkEventParams struct {
	NetworkID string
	EventType string
	TargetID  *string
	Status    *string
	Details   *string
	CreatedAt int64
}

func (q *Queries) InsertNetworkEvent(ctx context.Context, arg InsertNetworkEventParams) error {
	_, err := q.db.ExecContext(ctx, insertNetworkEvent,
		arg.NetworkID,
		arg.EventType,
		arg.TargetID,
		arg.Status,
		arg.Details,
		arg.CreatedAt,
	)
	return err
}

const listNetworkEvents = `-- name: ListNetworkEvents :many
SELECT e.id, e.network_id, e.event_type, e.target_id, e.status, e.details, e.created_at,
       n.hostname AS target_hostname
FROM network_events e
LEFT JOIN nodes n ON n.id = e.target_id
WHERE e.network_id = ?1
  AND e.created_at >= ?2
  AND (?3 IS NULL OR e.event_type = ?3)
ORDER BY e.created_at DESC, e.id DESC
LIMIT ?4
`

type ListNetworkEventsParams struct {
	NetworkID string
	Since     int64
	EventType interface{}
	Limit     int64
}

type ListNetworkEventsRow struct {
	ID             int64
	NetworkID      string
	EventType      string
	TargetID       *string
	Status         *string
	Details        *string
	CreatedAt      int64
	TargetHostname *string
}

func (q *Queries) ListNetworkEvents(ctx context.Context, arg ListNetworkEventsParams) ([]ListNetworkEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNetworkEvents,
		arg.NetworkID,
		arg.Since,
		arg.EventType,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNetworkEventsRow{}
	for rows.Next() {
		var i ListNetworkEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.EventType,
			&i.TargetID,
			&i.Status,
			&i.Details,
			&i.CreatedAt,
			&i.TargetHostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanStaleOnlineNodes = `-- name: ScanStaleOnlineNodes :many
SELECT id, network_id, hostname, last_seen_at
FROM nodes
WHERE status = 'online'
  AND node_type != 'lighthouse'
  AND (last_seen_at IS NULL OR last_seen_at < ?1)
`

type ScanStaleOnlineNodesRow struct {
	ID         string
	NetworkID  string
	Hostname   string
	LastSeenAt *int64
}

func (q *Queries) ScanStaleOnlineNodes(ctx context.Context, cutoff *int64) ([]ScanStaleOnlineNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, scanStaleOnlineNodes, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanStaleOnlineNodesRow{}
	for rows.Next() {
		var i ScanStaleOnlineNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.Hostname,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
