// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: network_members.sql

package dbsqlc

import (
	"context"
)

const deleteNetworkMember = `-- name: DeleteNetworkMember :exec
DELETE FROM network_members WHERE id = ?
`

func (q *Queries) DeleteNetworkMember(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNetworkMember, id)
	return err
}

const deleteNetworkMemberByNetworkAndUser = `-- name: DeleteNetworkMemberByNetworkAndUser :exec
DELETE FROM network_members WHERE network_id = ? AND user_id = ?
`

type DeleteNetworkMemberByNetworkAndUserParams struct {
	NetworkID string
	UserID    string
}

func (q *Queries) DeleteNetworkMemberByNetworkAndUser(ctx context.Context, arg DeleteNetworkMemberByNetworkAndUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteNetworkMemberByNetworkAndUser, arg.NetworkID, arg.UserID)
	return err
}

const getNetworkMember = `-- name: GetNetworkMember :one
SELECT id, network_id, user_id, role, created_at
FROM network_members WHERE network_id = ? AND user_id = ?
`

type GetNetworkMemberParams struct {
	NetworkID string
	UserID    string
}

func (q *Queries) GetNetworkMember(ctx context.Context, arg GetNetworkMemberParams) (NetworkMember, error) {
	row := q.db.QueryRowContext(ctx, getNetworkMember, arg.NetworkID, arg.UserID)
	var i NetworkMember
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const insertNetworkMember = `-- name: InsertNetworkMember :exec
INSERT INTO network_members (id, network_id, user_id, role)
VALUES (?, ?, ?, ?)
`

type InsertNetworkMemberParams struct {
	ID        string
	NetworkID string
	UserID    string
	Role      string
}

func (q *Queries) InsertNetworkMember(ctx context.Context, arg InsertNetworkMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertNetworkMember,
		arg.ID,
		arg.NetworkID,
		arg.UserID,
		arg.Role,
	)
	return err
}

const listMembersForNetwork = `-- name: ListMembersForNetwork :many
SELECT nm.id, nm.network_id, nm.user_id, nm.role, nm.created_at,
       u.email, u.name
FROM network_members nm
JOIN users u ON u.id = nm.user_id
WHERE nm.network_id = ?
ORDER BY nm.created_at
`

type ListMembersForNetworkRow struct {
	ID        string
	NetworkID string
	UserID    string
	Role      string
	CreatedAt int64
	Email     string
	Name      string
}

func (q *Queries) ListMembersForNetwork(ctx context.Context, networkID string) ([]ListMembersForNetworkRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembersForNetwork, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersForNetworkRow{}
	for rows.Next() {
		var i ListMembersForNetworkRow
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworkIDsForMember = `-- name: ListNetworkIDsForMember :many
SELECT network_id FROM network_members WHERE user_id = ?
`

func (q *Queries) ListNetworkIDsForMember(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNetworkIDsForMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var network_id string
		if err := rows.Scan(&network_id); err != nil {
			return nil, err
		}
		items = append(items, network_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
