// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package dbsqlc

import (
	"context"
	"database/sql"
)

const completeEnrollment = `-- name: CompleteEnrollment :exec
UPDATE nodes SET nebula_cert = ?, nebula_key = ?, hostname = ?, os = ?, arch = ?,
status = 'enrolled'
WHERE id = ?
`

type CompleteEnrollmentParams struct {
	NebulaCert []byte
	NebulaKey  []byte
	Hostname   string
	Os         string
	Arch       string
	ID         string
}

func (q *Queries) CompleteEnrollment(ctx context.Context, arg CompleteEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, completeEnrollment,
		arg.NebulaCert,
		arg.NebulaKey,
		arg.Hostname,
		arg.Os,
		arg.Arch,
		arg.ID,
	)
	return err
}

const consumeEnrollmentToken = `-- name: ConsumeEnrollmentToken :execresult
UPDATE nodes SET enrollment_token = NULL, enrollment_expires_at = NULL
WHERE id = ? AND enrollment_token = ?
`

type ConsumeEnrollmentTokenParams struct {
	ID              string
	EnrollmentToken *string
}

func (q *Queries) ConsumeEnrollmentToken(ctx context.Context, arg ConsumeEnrollmentTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, consumeEnrollmentToken, arg.ID, arg.EnrollmentToken)
}

const countNodesForNetwork = `-- name: CountNodesForNetwork :one
SELECT COUNT(*) FROM nodes WHERE network_id = ?
`

func (q *Queries) CountNodesForNetwork(ctx context.Context, networkID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNodesForNetwork, networkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = ?
`

func (q *Queries) DeleteNode(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const deleteNodesForNetwork = `-- name: DeleteNodesForNetwork :exec
DELETE FROM nodes WHERE network_id = ?
`

func (q *Queries) DeleteNodesForNetwork(ctx context.Context, networkID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodesForNetwork, networkID)
	return err
}

const getNodeByEnrollmentToken = `-- name: GetNodeByEnrollmentToken :one
SELECT id, network_id, hostname, os, arch, nebula_ip, agent_token, status
FROM nodes WHERE enrollment_token = ?
  AND (enrollment_expires_at IS NULL OR enrollment_expires_at > ?)
`

type GetNodeByEnrollmentTokenParams struct {
	EnrollmentToken     *string
	EnrollmentExpiresAt *int64
}

type GetNodeByEnrollmentTokenRow struct {
	ID         string
	NetworkID  string
	Hostname   string
	Os         string
	Arch       string
	NebulaIp   *string
	AgentToken string
	Status     string
}

func (q *Queries) GetNodeByEnrollmentToken(ctx context.Context, arg GetNodeByEnrollmentTokenParams) (GetNodeByEnrollmentTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getNodeByEnrollmentToken, arg.EnrollmentToken, arg.EnrollmentExpiresAt)
	var i GetNodeByEnrollmentTokenRow
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.NebulaIp,
		&i.AgentToken,
		&i.Status,
	)
	return i, err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, network_id, hostname, os, arch, nebula_cert, nebula_key, nebula_ip,
       agent_token, enrollment_token, agent_real_ip, status, last_seen_at, created_at
FROM nodes WHERE id = ?
`

type GetNodeByIDRow struct {
	ID              string
	NetworkID       string
	Hostname        string
	Os              string
	Arch            string
	NebulaCert      []byte
	NebulaKey       []byte
	NebulaIp        *string
	AgentToken      string
	EnrollmentToken *string
	AgentRealIp     *string
	Status          string
	LastSeenAt      *int64
	CreatedAt       int64
}

func (q *Queries) GetNodeByID(ctx context.Context, id string) (GetNodeByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getNodeByID, id)
	var i GetNodeByIDRow
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.Hostname,
		&i.Os,
		&i.Arch,
		&i.NebulaCert,
		&i.NebulaKey,
		&i.NebulaIp,
		&i.AgentToken,
		&i.EnrollmentToken,
		&i.AgentRealIp,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertNode = `-- name: InsertNode :exec
INSERT INTO nodes (id, network_id, hostname, os, arch, nebula_cert, nebula_key, nebula_ip, agent_token, enrollment_token, enrollment_expires_at, status)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNodeParams struct {
	ID                  string
	NetworkID           string
	Hostname            string
	Os                  string
	Arch                string
	NebulaCert          []byte
	NebulaKey           []byte
	NebulaIp            *string
	AgentToken          string
	EnrollmentToken     *string
	EnrollmentExpiresAt *int64
	Status              string
}

func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) error {
	_, err := q.db.ExecContext(ctx, insertNode,
		arg.ID,
		arg.NetworkID,
		arg.Hostname,
		arg.Os,
		arg.Arch,
		arg.NebulaCert,
		arg.NebulaKey,
		arg.NebulaIp,
		arg.AgentToken,
		arg.EnrollmentToken,
		arg.EnrollmentExpiresAt,
		arg.Status,
	)
	return err
}

const listNodeIPsForNetwork = `-- name: ListNodeIPsForNetwork :many
SELECT nebula_ip FROM nodes WHERE network_id = ? AND nebula_ip IS NOT NULL
`

func (q *Queries) ListNodeIPsForNetwork(ctx context.Context, networkID string) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, listNodeIPsForNetwork, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var nebula_ip *string
		if err := rows.Scan(&nebula_ip); err != nil {
			return nil, err
		}
		items = append(items, nebula_ip)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesForNetwork = `-- name: ListNodesForNetwork :many
SELECT id, network_id, hostname, os, arch, nebula_ip, agent_real_ip, status, last_seen_at, created_at
FROM nodes WHERE network_id = ? ORDER BY created_at ASC
`

type ListNodesForNetworkRow struct {
	ID          string
	NetworkID   string
	Hostname    string
	Os          string
	Arch        string
	NebulaIp    *string
	AgentRealIp *string
	Status      string
	LastSeenAt  *int64
	CreatedAt   int64
}

func (q *Queries) ListNodesForNetwork(ctx context.Context, networkID string) ([]ListNodesForNetworkRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodesForNetwork, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodesForNetworkRow{}
	for rows.Next() {
		var i ListNodesForNetworkRow
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.Hostname,
			&i.Os,
			&i.Arch,
			&i.NebulaIp,
			&i.AgentRealIp,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeAgentRealIP = `-- name: UpdateNodeAgentRealIP :exec
UPDATE nodes SET agent_real_ip = ? WHERE id = ?
`

type UpdateNodeAgentRealIPParams struct {
	AgentRealIp *string
	ID          string
}

func (q *Queries) UpdateNodeAgentRealIP(ctx context.Context, arg UpdateNodeAgentRealIPParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeAgentRealIP, arg.AgentRealIp, arg.ID)
	return err
}

const updateNodeCert = `-- name: UpdateNodeCert :exec
UPDATE nodes SET nebula_cert = ?, nebula_key = ? WHERE id = ?
`

type UpdateNodeCertParams struct {
	NebulaCert []byte
	NebulaKey  []byte
	ID         string
}

func (q *Queries) UpdateNodeCert(ctx context.Context, arg UpdateNodeCertParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeCert, arg.NebulaCert, arg.NebulaKey, arg.ID)
	return err
}

const updateNodeLastSeen = `-- name: UpdateNodeLastSeen :exec
UPDATE nodes SET last_seen_at = unixepoch(), status = 'online' WHERE id = ?
`

func (q *Queries) UpdateNodeLastSeen(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateNodeLastSeen, id)
	return err
}

const updateNodeStatus = `-- name: UpdateNodeStatus :exec
UPDATE nodes SET status = ? WHERE id = ?
`

type UpdateNodeStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeStatus, arg.Status, arg.ID)
	return err
}
