// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package dbsqlc

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string
	UserID    string
	ExpiresAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const getSessionUserID = `-- name: GetSessionUserID :one
SELECT user_id FROM sessions WHERE token = ? AND expires_at > ?
`

type GetSessionUserIDParams struct {
	Token     string
	ExpiresAt int64
}

func (q *Queries) GetSessionUserID(ctx context.Context, arg GetSessionUserIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSessionUserID, arg.Token, arg.ExpiresAt)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}
