// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbsqlc

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, name, password_hash, github_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	GithubID     *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.GithubID,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, github_id, created_at
FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.GithubID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, github_id, created_at
FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.GithubID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserProfileByID = `-- name: GetUserProfileByID :one
SELECT id, email, name FROM users WHERE id = ?
`

type GetUserProfileByIDRow struct {
	ID    string
	Email string
	Name  string
}

func (q *Queries) GetUserProfileByID(ctx context.Context, id string) (GetUserProfileByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserProfileByID, id)
	var i GetUserProfileByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}
