package main

import (
	"testing"

	"gopkg.in/yaml.v3"
)

// oldAgentConfig is a config generated by a pre-update agent (no punch_back,
// use_relays: true, mtu: 1300, no local_allow_list).
const oldAgentConfig = `pki:
  ca: /etc/hop-agent/ca.crt
  cert: /etc/hop-agent/node.crt
  key: /etc/hop-agent/node.key
static_host_map:
  "10.42.1.1": ["132.145.232.64:42001"]
lighthouse:
  am_lighthouse: false
  hosts:
    - "10.42.1.1"
relay:
  relays:
    - "10.42.1.1"
  use_relays: true
listen:
  host: 0.0.0.0
  port: 0
punchy:
  punch: true
  respond: true
tun:
  dev: nebula1
  mtu: 1300
firewall:
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: 41820
      proto: tcp
      groups:
        - admin
    - port: any
      proto: tcp
      groups:
        - node
    - port: any
      proto: icmp
      host: any
`

// userspaceConfig is a config with userspace TUN (no mtu field).
const userspaceConfig = `pki:
  ca: /etc/hop-agent/ca.crt
  cert: /etc/hop-agent/node.crt
  key: /etc/hop-agent/node.key
lighthouse:
  am_lighthouse: false
  hosts:
    - "10.42.1.1"
relay:
  relays:
    - "10.42.1.1"
  use_relays: true
punchy:
  punch: true
  respond: true
tun:
  user: true
firewall:
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: icmp
      host: any
`

func boolPtr(b bool) *bool { return &b }
func intPtr(i int) *int    { return &i }

// parseCfg is a test helper that unmarshals YAML into a generic map.
func parseCfg(t *testing.T, data []byte) map[string]interface{} {
	t.Helper()
	var cfg map[string]interface{}
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		t.Fatalf("failed to parse YAML: %v", err)
	}
	return cfg
}

func TestMergeNebulaConfig_UpdateUseRelays(t *testing.T) {
	update := &nebulaConfigUpdate{
		UseRelays: boolPtr(true),
	}

	out, changed, err := mergeNebulaConfig([]byte(oldAgentConfig), update)
	if err != nil {
		t.Fatal(err)
	}
	if !changed {
		t.Fatal("expected changed=true")
	}

	cfg := parseCfg(t, out)
	relay, ok := cfg["relay"].(map[string]interface{})
	if !ok {
		t.Fatal("relay section missing")
	}
	if relay["use_relays"] != true {
		t.Fatalf("expected use_relays=true, got %v", relay["use_relays"])
	}
	// Verify existing relay fields preserved.
	relays, ok := relay["relays"].([]interface{})
	if !ok || len(relays) == 0 {
		t.Fatal("relay.relays should be preserved")
	}
}

func TestMergeNebulaConfig_AddPunchBackAndDelay(t *testing.T) {
	update := &nebulaConfigUpdate{
		PunchBack:  boolPtr(true),
		PunchDelay: "1s",
	}

	out, changed, err := mergeNebulaConfig([]byte(oldAgentConfig), update)
	if err != nil {
		t.Fatal(err)
	}
	if !changed {
		t.Fatal("expected changed=true")
	}

	cfg := parseCfg(t, out)
	punchy, ok := cfg["punchy"].(map[string]interface{})
	if !ok {
		t.Fatal("punchy section missing")
	}
	if punchy["punch_back"] != true {
		t.Fatalf("expected punch_back=true, got %v", punchy["punch_back"])
	}
	if punchy["delay"] != "1s" {
		t.Fatalf("expected delay=1s, got %v", punchy["delay"])
	}
	// Verify existing punchy fields preserved.
	if punchy["punch"] != true {
		t.Fatal("punchy.punch should be preserved")
	}
	if punchy["respond"] != true {
		t.Fatal("punchy.respond should be preserved")
	}
}

// TestMergeNebulaConfig_IgnoresServerPushedMTU — as of v0.10.17 the
// agent intentionally ignores any server-pushed `tun.mtu`. The
// agent's local `nebulacfg.TunMTU` is the single source of truth
// (written by `ensureP2PConfig` at startup). Honoring server-pushed
// MTU let an older v0.10.15 control plane clobber a newer v0.10.16
// agent's correct local value during cert renewal — the bug this
// test guards against. If a per-network admin override is added
// later it MUST use a distinct field, not re-purpose `update.MTU`.
func TestMergeNebulaConfig_IgnoresServerPushedMTU(t *testing.T) {
	update := &nebulaConfigUpdate{
		MTU: intPtr(1400),
	}

	out, changed, err := mergeNebulaConfig([]byte(oldAgentConfig), update)
	if err != nil {
		t.Fatal(err)
	}
	// MTU was the only field in the update; with MTU now ignored the
	// merge must report no change so we don't churn the file on disk.
	if changed {
		t.Fatal("expected changed=false: server-pushed MTU must be ignored")
	}

	cfg := parseCfg(t, out)
	tun, ok := cfg["tun"].(map[string]interface{})
	if !ok {
		t.Fatal("tun section missing")
	}
	// Original yaml had mtu: 1300 — must be untouched by the server push.
	if tun["mtu"] != 1300 {
		t.Fatalf("local mtu should be untouched (want 1300), got %v", tun["mtu"])
	}
	if tun["dev"] != "nebula1" {
		t.Fatalf("tun.dev should be preserved, got %v", tun["dev"])
	}
}

func TestMergeNebulaConfig_SkipMTU_UserspaceMode(t *testing.T) {
	update := &nebulaConfigUpdate{
		MTU: intPtr(1400),
	}

	out, changed, err := mergeNebulaConfig([]byte(userspaceConfig), update)
	if err != nil {
		t.Fatal(err)
	}
	if changed {
		t.Fatal("expected changed=false for userspace config with MTU update")
	}

	cfg := parseCfg(t, out)
	tun, ok := cfg["tun"].(map[string]interface{})
	if !ok {
		t.Fatal("tun section missing")
	}
	if _, hasMTU := tun["mtu"]; hasMTU {
		t.Fatal("mtu should NOT be added to userspace config")
	}
}

func TestMergeNebulaConfig_NilUpdate_NoChange(t *testing.T) {
	update := &nebulaConfigUpdate{}

	_, changed, err := mergeNebulaConfig([]byte(oldAgentConfig), update)
	if err != nil {
		t.Fatal(err)
	}
	if changed {
		t.Fatal("expected changed=false for empty update")
	}
}

func TestMergeNebulaConfig_FullUpdate_PreservesUnrelatedFields(t *testing.T) {
	update := &nebulaConfigUpdate{
		UseRelays:  boolPtr(true),
		PunchBack:  boolPtr(true),
		PunchDelay: "1s",
		MTU:        intPtr(1400),
	}

	out, changed, err := mergeNebulaConfig([]byte(oldAgentConfig), update)
	if err != nil {
		t.Fatal(err)
	}
	if !changed {
		t.Fatal("expected changed=true")
	}

	cfg := parseCfg(t, out)

	// Verify unrelated fields are preserved.
	pki, ok := cfg["pki"].(map[string]interface{})
	if !ok {
		t.Fatal("pki section missing")
	}
	if pki["ca"] != "/etc/hop-agent/ca.crt" {
		t.Fatalf("pki.ca should be preserved, got %v", pki["ca"])
	}

	lighthouse, ok := cfg["lighthouse"].(map[string]interface{})
	if !ok {
		t.Fatal("lighthouse section missing")
	}
	if lighthouse["am_lighthouse"] != false {
		t.Fatal("lighthouse.am_lighthouse should be preserved as false")
	}

	listen, ok := cfg["listen"].(map[string]interface{})
	if !ok {
		t.Fatal("listen section missing")
	}
	if listen["port"] != 0 {
		t.Fatalf("listen.port should be preserved, got %v", listen["port"])
	}

	fw, ok := cfg["firewall"].(map[string]interface{})
	if !ok {
		t.Fatal("firewall section missing")
	}
	inbound, ok := fw["inbound"].([]interface{})
	if !ok || len(inbound) == 0 {
		t.Fatal("firewall.inbound rules should be preserved")
	}
}

func TestMergeNebulaConfig_PartialPunchyUpdate(t *testing.T) {
	update := &nebulaConfigUpdate{
		PunchBack: boolPtr(true),
	}

	out, changed, err := mergeNebulaConfig([]byte(oldAgentConfig), update)
	if err != nil {
		t.Fatal(err)
	}
	if !changed {
		t.Fatal("expected changed=true")
	}

	cfg := parseCfg(t, out)
	punchy := cfg["punchy"].(map[string]interface{})
	if punchy["punch_back"] != true {
		t.Fatal("punch_back should be set")
	}
	if _, hasDelay := punchy["delay"]; hasDelay {
		t.Fatal("delay should NOT be added when not in update")
	}
}

func TestMergeNebulaConfig_InvalidYAML(t *testing.T) {
	update := &nebulaConfigUpdate{PunchBack: boolPtr(true)}

	_, _, err := mergeNebulaConfig([]byte("not: valid: yaml: {{"), update)
	if err == nil {
		t.Fatal("expected error for invalid YAML")
	}
}

func TestMergeNebulaConfig_OutputIsValidYAML(t *testing.T) {
	update := &nebulaConfigUpdate{
		UseRelays:  boolPtr(true),
		PunchBack:  boolPtr(true),
		PunchDelay: "1s",
		MTU:        intPtr(1400),
	}

	out, _, err := mergeNebulaConfig([]byte(oldAgentConfig), update)
	if err != nil {
		t.Fatal(err)
	}

	var roundTrip map[string]interface{}
	if err := yaml.Unmarshal(out, &roundTrip); err != nil {
		t.Fatalf("output is not valid YAML: %v\n---\n%s", err, string(out))
	}
}

func TestMergeNebulaConfig_UpdateListenPort(t *testing.T) {
	update := &nebulaConfigUpdate{
		ListenPort: intPtr(4242),
	}

	out, changed, err := mergeNebulaConfig([]byte(oldAgentConfig), update)
	if err != nil {
		t.Fatal(err)
	}
	if !changed {
		t.Fatal("expected changed=true")
	}

	cfg := parseCfg(t, out)
	listen, ok := cfg["listen"].(map[string]interface{})
	if !ok {
		t.Fatal("listen section missing")
	}
	if listen["port"] != 4242 {
		t.Fatalf("expected port=4242, got %v", listen["port"])
	}
	// Verify host preserved.
	if listen["host"] != "0.0.0.0" {
		t.Fatalf("listen.host should be preserved, got %v", listen["host"])
	}
}

func TestMergeNebulaConfig_UpdateListenPortFromZero(t *testing.T) {
	// Simulate config with port: 0 (the old default we're replacing).
	configWithPort0 := `listen:
  host: 0.0.0.0
  port: 0
punchy:
  punch: true
`
	update := &nebulaConfigUpdate{
		ListenPort: intPtr(4242),
	}

	out, changed, err := mergeNebulaConfig([]byte(configWithPort0), update)
	if err != nil {
		t.Fatal(err)
	}
	if !changed {
		t.Fatal("expected changed=true")
	}

	cfg := parseCfg(t, out)
	listen := cfg["listen"].(map[string]interface{})
	if listen["port"] != 4242 {
		t.Fatalf("expected port=4242, got %v", listen["port"])
	}
}

func TestMergeNebulaConfig_FullUpdateWithListenPort(t *testing.T) {
	update := &nebulaConfigUpdate{
		UseRelays:  boolPtr(true),
		PunchBack:  boolPtr(true),
		PunchDelay: "1s",
		MTU:        intPtr(1400),
		ListenPort: intPtr(4242),
	}

	out, changed, err := mergeNebulaConfig([]byte(oldAgentConfig), update)
	if err != nil {
		t.Fatal(err)
	}
	if !changed {
		t.Fatal("expected changed=true")
	}

	cfg := parseCfg(t, out)

	// Verify all fields updated.
	relay := cfg["relay"].(map[string]interface{})
	if relay["use_relays"] != true {
		t.Fatal("use_relays should be true")
	}
	punchy := cfg["punchy"].(map[string]interface{})
	if punchy["punch_back"] != true {
		t.Fatal("punch_back should be true")
	}
	if punchy["delay"] != "1s" {
		t.Fatal("delay should be 1s")
	}
	tun := cfg["tun"].(map[string]interface{})
	// MTU is intentionally ignored as of v0.10.17 (server-pushed mtu
	// is no longer honored — see TestMergeNebulaConfig_IgnoresServerPushedMTU).
	// Even though the update specified mtu: 1400, the agent must keep
	// its local value (oldAgentConfig has mtu: 1300).
	if tun["mtu"] != 1300 {
		t.Fatalf("mtu should be untouched (want 1300), got %v", tun["mtu"])
	}
	listen := cfg["listen"].(map[string]interface{})
	if listen["port"] != 4242 {
		t.Fatal("port should be 4242")
	}

	// Verify unrelated fields preserved.
	pki := cfg["pki"].(map[string]interface{})
	if pki["ca"] != "/etc/hop-agent/ca.crt" {
		t.Fatal("pki.ca should be preserved")
	}
}
